azimuth-cloud/capi-helm-charts

utils/bin/make-chart
Manifests with identical `apiVersion`,`kind` and `name` can create resources in different namespaces. Currently, only the resource that `kustomize`/`kubectl` evaluates last is created by `helm upgrade --install`, because the template files of the preceding resources are overwritten by later ones.
This adds resource `namespace` (if it exists) to the helm template filename created by `make-chart` to disambiguate identical resources created in different namespaces.
=> Add namespace to helm template filename

charts/cluster-addons/templates/cni/cilium.yaml
The default IPAM mode with Cilium is [cluster scope](https://docs.cilium.io/en/stable/concepts/networking/ipam/), this commit switches back to this default so that there are no surprises when provisioning a cluster (i.e if you don't annotate nodes)
=> [cilium] Switch the IPAM mode to the default

charts/cluster-addons/values.yaml
Supersedes #5 I guess? Tested on a helm installed capi-cluster and verified that GPU metrics now appear in Grafana.
=> Enable Nvidia ServiceMonitor

charts/openstack-cluster/templates/control-plane/openstack-machine-template.yaml, charts/openstack-cluster/templates/node-group/openstack-machine-template.yaml, charts/openstack-cluster/values.yaml
When used in Azimuth, this will allow the volume type and AZ to be specified globally or by the template while allowing the individual cluster to specify volume sizes without worrying about conditional merges.
=> Make rootVolume dependent on disk size being specified

.github/scripts/generate-app-token, .github/scripts/requirements.txt, .github/workflows/update-dependencies.yml
This PR adds the ability to use a GitHub App token to authenticate PRs that are created to update dependencies. This means that those PRs will be able to trigger automation like the PR tests.
=> Use an app token so that automation PRs trigger workflows

.github/workflows/ensure-capi-images.yaml
Azimuth is using focal images due to an issue with Harbor, so that is what we should test for now.
=> Test focal images

charts/cluster-addons/templates/_helpers.tpl, charts/cluster-addons/templates/cni/calico.yaml, charts/cluster-addons/templates/cni/cilium.yaml, charts/cluster-addons/templates/ingress-nginx.yaml, charts/cluster-addons/templates/kubernetes-dashboard.yaml, charts/cluster-addons/templates/mellanox-network-operator.yaml, charts/cluster-addons/templates/metrics-server.yaml, charts/cluster-addons/templates/monitoring/kube-prometheus-stack.yaml, charts/cluster-addons/templates/monitoring/loki-stack.yaml, charts/cluster-addons/templates/nfd.yaml, charts/cluster-addons/templates/nvidia-gpu-operator.yaml, charts/cluster-addons/templates/openstack/ccm.yaml, charts/cluster-addons/templates/openstack/csi-cinder.yaml, charts/cluster-addons/values.yaml, charts/openstack-cluster/templates/_helpers.tpl, charts/openstack-cluster/templates/autoscaler/deployment.yaml, charts/openstack-cluster/values.yaml
This completes the work done in #93.
The `imagePrefix` has caught us out a few times with changes to repositories, and is a nightmare to maintain. It is being removed in favour of implicit mirroring.
=> Remove image prefix

charts/openstack-cluster/templates/control-plane/kubeadm-control-plane.yaml, charts/openstack-cluster/templates/control-plane/openstack-machine-template.yaml, charts/openstack-cluster/templates/node-group/machine-deployment.yaml, charts/openstack-cluster/templates/node-group/openstack-machine-template.yaml, charts/openstack-cluster/values.yaml
To satisfy the [version skew policy](https://kubernetes.io/releases/version-skew-policy/) it would be useful if 
control plane and machine deployment nodes could be updated separately. This would allow us to update the control plane first and then update the worker nodes.
This checks if machineImage and kubernetesVersion are defined for the separate control plane/nodegroup and falls back to the root one if not.
~~Allow separate (or no) imagePrefix for addons~~
=> Separate machine image for control plane and worker nodes

charts/openstack-cluster/README.md, charts/openstack-cluster/templates/_helpers.tpl, charts/openstack-cluster/templates/control-plane/kubeadm-control-plane.yaml, charts/openstack-cluster/templates/node-group/kubeadm-config-template.yaml, charts/openstack-cluster/values.yaml
* Modify openstack-cluster templates to integrate ignition components for Flatcar
* Smaller changes related to addon defaults
=> Flatcar integration

charts/cluster-addons/README.md, charts/cluster-addons/templates/openstack/k8s-keystone-auth.yaml, charts/cluster-addons/values.yaml, charts/openstack-cluster/README.md, charts/openstack-cluster/templates/_helpers.tpl, charts/openstack-cluster/templates/control-plane/kubeadm-control-plane.yaml, charts/openstack-cluster/templates/node-group/kubeadm-config-template.yaml, charts/openstack-cluster/values.yaml
* Add template for basic kube-apiserver webhook based authN/authZ 
* Add support for deploying sub chart based on https://github.com/heytrav/helm-charts/tree/main/charts/k8s-keystone-auth
=> Add configuration for keystone webhook

charts/cluster-addons/values.yaml
=> Revert ingress-nginx to 4.8.3

charts/openstack-cluster/templates/control-plane/kubeadm-control-plane.yaml, charts/openstack-cluster/values.yaml
Use control plane remediation strategy to prevent the control plane from infinitely remediating.
=> Prevent infinite control plane remediations

charts/openstack-cluster/values.yaml
This should reduce node churn in the case of a transient issue, e.g. a network problem prevents access to OpenStack APIs.
=> Use less aggressive node startup timeouts

.github/workflows/update-addons.yml, charts/cluster-addons/grafana-dashboards/blackbox-exporter-dashboard.json, charts/cluster-addons/templates/cni/calico.yaml, charts/cluster-addons/templates/ingress-nginx.yaml, charts/cluster-addons/templates/monitoring/blackbox-exporter.yaml, charts/cluster-addons/templates/monitoring/kube-prometheus-stack.yaml, charts/cluster-addons/templates/monitoring/loki-stack.yaml, charts/cluster-addons/values.yaml, skopeo-manifests/prometheus-blackbox-exporter.yaml
Add the blackbox exporter, dashboard and alerting rules. The exporter is configured with the OpenStack auth URL of the target cloud by default. Additional targets can be added by creating more `ServiceMonitor`s with the required targets.
Also fixed up broken dashboards and alerts for other components.
=> Add blackbox exporter addon

charts/cluster-addons/templates/metrics-server.yaml
Pods for the metrics-server are currently in `kube-system` without a pod disruption budget, which is a category of pods that prevent scale down in auto-scaling clusters.
=> Add pod disruption budget to metrics-server

charts/openstack-cluster/templates/autoscaler/deployment.yaml, charts/openstack-cluster/templates/autoscaler/role.yaml, charts/openstack-cluster/values.yaml
In particular, allow pods with `emptyDir`s to be evicted, switch to the `least-waste` expander and increase the default log level.
=> Improve cluster autoscaler default config

charts/openstack-cluster/templates/cluster-openstack.yaml
* allowedCidrs is separate from loadBalancerProvider but was being rendered as child of that key.
=> Reduce indentation of allowedCidrs

charts/cluster-addons/templates/cni/calico.yaml, charts/cluster-addons/values.yaml
* Use calico GlobalNetworkPolicy to deny egress to metaservice
* basic values to for priority, deny and allow CIDR
=> Add global network policy to block access to metaservice

charts/openstack-cluster/templates/autoscaler/role.yaml
Before:
```
I0311 09:22:36.221441       1 reflector.go:325] Listing and watching cluster.x-k8s.io/v1beta1, Resource=machinepools from k8s.io/client-go/dynamic/dynamicinformer/informer.go:108
I0311 09:22:36.221649       1 round_trippers.go:463] GET https://10.43.0.1:443/apis/cluster.x-k8s.io/v1beta1/namespaces/az-stackhpc-lab/machinepools?limit=500&resourceVersion=0
W0311 09:22:36.223185       1 reflector.go:539] k8s.io/client-go/dynamic/dynamicinformer/informer.go:108: failed to list cluster.x-k8s.io/v1beta1, Resource=machinepools: machinepools.cluster.x-k8s.io is forbidden: User "system:serviceaccount:az-stackhpc-lab:scott-autoscaling-test-autoscaler" cannot list resource "machinepools" in API group "cluster.x-k8s.io" in the namespace "az-stackhpc-lab"
E0311 09:22:36.223209       1 …
```
=> Add machinepool verbs to autoscaler role

charts/cluster-addons/values.yaml
Just discovered that the image referenced in helm chart doesn't exist. Updated with a version that has an existing image.
=> Update k8s-keystone-auth subchart with working image

charts/openstack-cluster/templates/_helpers.tpl
Sorts the node-labels whilst iterating through the keys of the un-ordered dict. This prevents a machine deployment flipping between n machine-sets.
Currently, each evaluation of the template could result in a different label order. Since the entire resource is hashed, this results in "upgrades" back and forth, depending on where we land in the unordered dict.
By sorting the keys, we at least ensure that the results are idempotent between helm template (or equiv.) runs.
I'm sure there's other places we rely on range implicitly being ordered, but doing a quick grep through, the other uses of range in openstack-cluster/helpers.tpl appear to not require this from a glance.
Testing
-----------
I've tested this locally with the following:
- Create multiple machine deployments to increase the …
=> Sort node-labels whilst iterating over keys

charts/openstack-cluster/values.yaml
As discussed elsewhere, we now have feature enabled which blocks all worker node remediation if control plane is unhealthy, so should be safe to reset worker remediation threshold to 100% without the risk of runaway remediations seen previously.
=> Increase worker node maxUnhealthy remediation threshold to 100%

charts/cluster-addons/values.yaml
Make CSI cinder controller plugin and tigera-operator schedule to control plane nodes.
This is to avoid pods being "unevictable" for cluster autoscaler
=> Pods affinity for control plane nodes

.github/values/arcus/latest-addons.yaml, .github/values/leafcloud/latest-addons.yaml, .github/workflows/test.yaml, charts/cluster-addons/templates/cni/calico.yaml
In 3.28 Calico starting creating the `calico-typha-metrics` service itself, breaking our existing metric integration. This PR fixes that, protects against similar things happening in the future and introduces a new test that would have caught the issue.
**NOTE** - the "deploy from previous tag" in the `chart-upgrade` test will fail because of this bug, so the failure of that test will not block merging.
=> Fix broken Calico metrics

charts/openstack-cluster/README.md
The docs currently provide configuration for using the OVN load-balancer provider, but the default lb-method provided by CCM is `ROUND_ROBIN`, which is not compatible with OVN based load balancers.   When attempting to use OVN with `ROUND_ROBIN`, CCM will error with:
`"Provider 'ovn' does not support a requested option: OVN provider does not support ROUND_ROBIN algorithm"`
=> added note about using SOURCE_IP_PORT for the lb-method with OVN

CODEOWNERS, charts/cluster-addons/values.yaml
Workaround for https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/2333
=> Allow OCCM to manage LB security groups

CODEOWNERS, charts/cluster-addons/values.yaml
It turns out that the OpenStack cloud-controller-manager is not very good at managing security groups, particularly when cluster nodes are deleted and recreated. We've decided that a better solution for now is to revert this and instead pin CAPO to an older working version.
=> Revert "Allow OCCM to manage LB security groups (#469)"

.github/values/arcus/base.yaml, .github/values/leafcloud/base.yaml, CODEOWNERS, charts/openstack-cluster/README.md, charts/openstack-cluster/templates/secret-cloud-config.yaml
Looks like this was fixed upstream at some point since the Gophercloud [type definition](https://github.com/gophercloud/gophercloud/blob/master/openstack/config/clouds/types.go#L86) now allows the project ID to be omitted.
=> Drop requirement for project ID field in cloud credentials

.github/actions/upgrade-and-test/action.yml, .github/actions/upload-logs/action.yml
Fixes failing CI due to https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> Bump upload-artifact action to v4

charts/cluster-addons/templates/cni/calico.yaml
The manifest source targets {{ cluster-name }}, however the Calico operator creates a GlobalNetworkPolicy on the child with default.{{ cluster-name}}. 
This works fine until there's a diff, then the manifest will fail to apply/patch because K8s requires a delete and recreate for name changes.
I suspect default comes from the tier automatically applied by the operator: `projectcalico.org/tier=default`
We've seen some clusters which have sat retrying for 20K+ attempts, but because the update is usually an annotation the cluster continues fine, so it's probably been missed for a while. I've also tested this on a fresh cluster, and it still deploys with the correct resource name in the child (i.e. it doesn't become `default.default.{cluster-name}...`)
To test:
- Deploy a cluster without this …
=> Prepend default to GlobalNetPolicy manifest name

charts/openstack-cluster/templates/node-group/machine-deployment.yaml
Example templating errors:
Invalid character:
```
% helm template test charts/openstack-cluster -f values-test.yml --set "nodeGroups[0].name=abc.d"
Error: execution error at (openstack-cluster/templates/node-group/machine-deployment.yaml:4:3): Node group name must be at least three characters long and must contain only lower-case alphanumeric characters and dashes (found name: abc.d)
```
Name too short:
```
% helm template test charts/openstack-cluster -f values-test.yml --set "nodeGroups[0].name=ab"
Error: execution error at (openstack-cluster/templates/node-group/machine-deployment.yaml:4:3): Node group name must be at least three characters long and must contain only lower-case alphanumeric characters and dashes (found name: ab)
```
=> Add node group name validation during templating

charts/openstack-cluster/values.yaml
It has been the default since 1.29
And it was removed in k8s 1.33.0
https://github.com/kubernetes/kubernetes/pull/130162/files
=> Remove api-server cloud provider flag

charts/openstack-cluster/templates/node-group/machine-deployment.yaml
Previous version lead to a mangled `helm template` output when two or more node groups were specified.
Old template output included:
```
nodeDeletionTimeout: 5m0s---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
```
fixed version templates correctly as:
```
nodeDeletionTimeout: 5m0s
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
```
=> Fix whitespace in node group name check

.github/workflows/update-addons.yml
The Intel GPU plugin Helm chart only deploys CRDs which refer to its associated image in a non-standard location, so an additional images field is necessary
=> Added GPU plugin images to Intel dependencies

charts/openstack-cluster/templates/cluster-openstack.yaml, charts/openstack-cluster/values.yaml
The `dnsNameservers` value has moved into `managedSubnets` section, but was trying to reference `.internalNetwork.dnsNameservers` which does not exist in chart values.
This change removes the context switch into `internalNetwork` to allow all references to correctly find their related values.
Closes: https://github.com/azimuth-cloud/capi-helm-charts/issues/476
=> Update dnsNameservers context to pick up values

.github/workflows/lint.yaml, CONTRIBUTING.md, charts/openstack-cluster/tests/__snapshot__/snapshot_base_test.yaml.snap, charts/openstack-cluster/tests/__snapshot__/snapshot_full_test.yaml.snap
Minor fixes which weren't caught previously since Helm lint CI uses pull request target trigger so wasn't properly tested until #546 was merged.
=> Update manifest snapshots

charts/etcd-defrag/templates/cronjob.yaml, charts/etcd-defrag/values.yaml, charts/openstack-cluster/tests/__snapshot__/snapshot_base_test.yaml.snap, charts/openstack-cluster/tests/__snapshot__/snapshot_full_test.yaml.snap, skopeo-manifests/etcd-defrag.yaml
Bitnami recently paywalled their image updates so we need another source. Unfortunately there doesn't seem to be anyone else who publishes tags without the k8s patch version appended to allow us to always use the latest patch version, so we have to default to the full semver tag instead.
=> Switch to from bitnami/kubectl to rancher/kubectl image
